apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: server1
spec:
  selector:
    matchLabels:
      app: server1
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
      - name: server1
        image: marcel1111154/server:v1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi